spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración para PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Para evitar errores de encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true