name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tienda
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven

      - name: Cache SonarCloud packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Verify token and project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "Verificando token..."
          curl -s -X GET "https://sonarcloud.io/api/users/current" \
            -H "Authorization: Bearer $SONAR_TOKEN"
          echo ""
          echo "Verificando proyecto..."
          curl -s -X GET "https://sonarcloud.io/api/projects/search?organization=GabMlopez&projects=GabMlopez_Aseg_par_1" \
            -H "Authorization: Bearer $SONAR_TOKEN"

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify sonar:sonar -Dsonar.token=$SONAR_TOKEN -Dsonar.organization=GabMlopez -Dsonar.projectKey=GabMlopez_Aseg_par_1 -Dsonar.host.url=https://sonarcloud.io